// Local environment
### Get all contacts
GET http://localhost:8080/contacts

### Get contact by ID (John Doe)
GET http://localhost:8080/contacts/6820d1cf789394cf10687f07

### Get contact by ID (Jane Smith)
GET http://localhost:8080/contacts/6820d1cf789394cf10687f08

### Get contact by ID (Michael Johnson)
GET http://localhost:8080/contacts/6820d1cf789394cf10687f09

// Production environment
### Get all contacts
GET https://cse341-7pys.onrender.com/contacts

### Get contact by ID (John Doe)
GET https://cse341-7pys.onrender.com/contacts/6820d1cf789394cf10687f07

### Get contact by ID (Jane Smith)
GET https://cse341-7pys.onrender.com/contacts/6820d1cf789394cf10687f08

### Get contact by ID (Michael Johnson)
GET https://cse341-7pys.onrender.com/contacts/6820d1cf789394cf10687f09